defaultPortal: ProductCards
portals:
  - name: ProductCards
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CL_3moeQMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFOyHUCkcHzE6Lp7D0SsESTuU0rQ-OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQdLG0MH-8CYG5Td9TTbWuxbDxcvUoDbmExUgBaAA
        expiresAt: '2022-05-26T15:05:30.307Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
