defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKC24KKHMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFA-73nE0a82K9haqtJbXKVHve4XsOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhS9iw4_PC_DmC0H-A43y96bSEigskoDbmExUgBaAA
        expiresAt: '2022-04-29T08:02:52.836Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
