defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPGI7PaKMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFI86QydmVD6z3f1pO6a-Ox7RekkSOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQjb2Ae-tn94IyWlRSq2TFIKd4y1EoDbmExUgBaAA
        expiresAt: '2022-05-10T16:43:50.782Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
