defaultPortal: ProductCards
portals:
  - name: ProductCards
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJGtr42QMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFDxm1FEn77DYiBDvhznbb-UHMZOvOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTJ7W9KGdUdHZrYXBAc_jgHrZHWAkoDbmExUgBaAA
        expiresAt: '2022-05-26T18:40:47.765Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
