defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMLul5yAMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFBA_so9pY2jX094UzlyFbNsWrp1nOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSmr39Ow_tF8tIsP2EtTKt1THRFk0oDbmExUgBaAA
        expiresAt: '2022-04-07T10:15:52.901Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
