defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPif44OOMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFD7LKRXdaD-WCaz9bYuxGSqxyotlOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhR3nWqHlmJ8huufMkuaR9jNF1CEOEoDbmExUgBaAA
        expiresAt: '2022-05-20T07:57:35.612Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
