defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIaEudeNMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFC4qkbmNDo3x0wzK52ijaiWULNMKOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRcpnk5AiIIFUowpwrPocS0CLsGt0oDbmExUgBaAA
        expiresAt: '2022-05-19T06:08:09.225Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
