defaultPortal: ProductCards
portals:
  - name: ProductCards
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJjD58uRMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFLsLlHWvYBQzx6z_W3ZgG9boHTuLOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhS6OrFuF2uZ2sE-q4kYb3ToAxwlbEoDbmExUgBaAA
        expiresAt: '2022-05-31T09:37:06.972Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
