defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COywwb2NMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFGLvo5DQc4n8-24TaJX83gQLW-p5OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQX6fsxgLeHHzxsVHta_lK9GozrnkoDbmExUgBaAA
        expiresAt: '2022-05-18T15:01:40.079Z'
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
