defaultPortal: sandbox
portals:
  - name: sandbox
    portalId: 20686580
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
<<<<<<< Updated upstream
          COywwb2NMBIJAA0AAAAA4A0DGPTN7gkgyfSQDSju6QwyFGLvo5DQc4n8-24TaJX83gQLW-p5OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQX6fsxgLeHHzxsVHta_lK9GozrnkoDbmExUgBaAA
        expiresAt: '2022-05-18T15:01:40.079Z'
=======
          CLjzlc2UMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFLwSgl-7qOzuXcYhVflgrYNtnLecOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTojEe_vrpQM3fLMxTRc_6rWbaM0koDbmExUgBaAA
        expiresAt: '2022-06-09T18:06:30.332Z'
>>>>>>> Stashed changes
    personalAccessKey: >-
      CiQwNDBkMWMwMC0xMzEwLTQxNWEtYjAxMS0zNDYzYjA4ZDhiYWIQ9M3uCRjJ9JANKhkABeaRgm2vQnjMhHrB19BnSLUN00U24EwvSgNuYTE
