defaultPortal: ProductCards
portals:
  - name: ProductCards
    portalId: 6412394
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMb2y4aiMBIJAA0AAAAAAAwDGOqwhwMg15iPDCju6QwyFDrNuduSTsquwgs6iz6uKX2jgvfUOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAAAAADwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQCbAJFN4HfJ1TsAX3HIa5at--Nq0oDbmExUgBaAA
        expiresAt: '2022-07-21T12:54:34.058Z'
    personalAccessKey: >-
      CiQyMWMyMTE5Yy1mNTk5LTQ2MWMtYjcyOC0zNmE2ZGE0ZmVmNjAQ6rCHAxjXmI8MKhkABeaRgmJRDX3U_UjwtdRz8_63CBIAvABnSgNuYTE
